add a safety check to benchmark uploads

diff --git a/.github/workflows/bench_upload_for_pr.yaml b/.github/workflows/bench_upload_for_pr.yaml
--- a/.github/workflows/bench_upload_for_pr.yaml
+++ b/.github/workflows/bench_upload_for_pr.yaml
@@ -3,7 +3,7 @@ name: Benchmark upload
 #
 # This workflow runs after every benchmark, to upload the report to S3.
 #
-# It is its own workflow, because PRs can contain malicious code and run in a context with secrets..
+# It is its own workflow and starts with a safety check, because PRs can contain malicious code and run in a context with secrets..
 #
 # See also https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
 #
@@ -14,12 +14,51 @@ on:
     types:
       - completed
 
+permissions:
+  actions: read
+  contents: read
+  pull-requests: read
+
 jobs:
   upload:
     name: Upload benchmark report
     runs-on: warp-ubuntu-latest-x64-16x
     if: github.event.workflow_run.conclusion == 'success'
     steps:
+      - name: Safety check
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
+          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
+        run: |
+
+          # Was triggering workflow triggered by a PR?
+
+          PR_NUMBER=$(gh api /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} \
+                      --jq '.pull_requests[0].number')
+
+          if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
+            echo "No PR associated with this the triggering workflow run: ${{ github.event.workflow_run.id }}."
+            exit 0
+          fi
+
+          # Were workflow files changed in the PR?
+
+          CHANGED_FILES=$(gh api /repos/${{ github.repository }}/pulls/$PR_NUMBER/files --jq '.[].filename')
+
+          echo -e "These files were modified in PR #$PR_NUMBER which triggered workflow run ${{ github.event.workflow_run.id }}:\n$CHANGED_FILES"
+
+          if echo "$CHANGED_FILES" | grep -q "^\.github/workflows/"; then
+            echo -e "\n## :x: Error\nWorkflow file change detected. Failing the workflow for security reasons." >> $GITHUB_STEP_SUMMARY
+
+            curl --silent -d 'text=A workflow file change was included in <https://github.com/flashbots/rbuilder/pull/'"$PR_NUMBER"'|PR '"$PR_NUMBER"'>.' \
+                -d "channel=$SLACK_CHANNEL" -H "Authorization: Bearer $SLACK_TOKEN" -X POST https://slack.com/api/chat.postMessage > /dev/null 2>&1
+
+            exit 1
+          else
+            echo "No workflow file changes detected."
+          fi
+
       # https://github.com/actions/download-artifact
       - uses: actions/download-artifact@v4
         with:
@@ -35,8 +74,11 @@ jobs:
       - name: Prepare variables
         id: prepare
         run: |
-          cat benchmark-report/vars.txt
-          source benchmark-report/vars.txt
+          while IFS='=' read -r key value; do
+            if [[ $key && $value ]]; then
+              export "$key=$value"
+            fi
+          done < benchmark-report/vars.txt
 
           S3_UPLOAD_DIR="benchmark/${HEAD_SHA_SHORT}-${BASE_SHA_SHORT}"
           echo "S3_UPLOAD_DIR=${S3_UPLOAD_DIR}" >> "$GITHUB_OUTPUT"
